project:
  type: website

website:
  title: "AUSTIN CAN HELP"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/austinyhc
      - icon: twitter
        href: https://twitter.com/austinyht
format:
  html:
    theme: cosmo
    css: styles.css



